window.queens = {
"Bebe Zahara Benet": { season: "1", placement: "1", country: "🇺🇸", image: "images/US Queens/BeBeZaharaBenetS1CastMug.webp" },
"Nina Flowers": { season: "1", placement: "2", country: "🇺🇸", image: "images/US Queens/NinaFlowersS1CastMug.webp" },
"Rebecca Glasscock": { season: "1", placement: "3", country: "🇺🇸", image: "images/US Queens/RebeccaGlasscockS1CastMug.webp" },
"Shannel": { season: "1", placement: "4", country: "🇺🇸", image: "images/US Queens/ShannelS1CastMug.webp" },
"Ongina": { season: "1", placement: "5", country: "🇺🇸", image: "images/US Queens/OnginaS1CastMug.webp" },
"Jade": { season: "1", placement: "6", country: "🇺🇸", image: "images/US Queens/JadeSotomayorS1CastMug.webp" },
"Akashia": { season: "1", placement: "7", country: "🇺🇸", image: "images/US Queens/AkashiaS1CastMug.webp" },
"Tammie Brown": { season: "1", placement: "8", country: "🇺🇸", image: "images/US Queens/TammieBrownS1CastMug.webp" },
"Victoria Porkchop Parker": { season: "1", placement: "9", country: "🇺🇸", image: "images/US Queens/VictoriaParkerS1CastMug.webp" },
"Raven": { season: "2", placement: "2", country: "🇺🇸", image: "images/US Queens/RavenS2CastMug.webp" },
"Jujubee": { season: "2", placement: "3", country: "🇺🇸", image: "images/US Queens/JujubeeS2CastMug.webp" },
"Tatianna": { season: "2", placement: "4", country: "🇺🇸", image: "images/US Queens/TatiannaS2CastMug.webp" },
"Pandora Boxx": { season: "2", placement: "5", country: "🇺🇸", image: "images/US Queens/PandoraBoxxS2CastMug.webp" },
"Jessica Wild": { season: "2", placement: "6", country: "🇺🇸", image: "images/US Queens/JessicaWildS2CastMug.webp" },
"Sahara Davenport": { season: "2", placement: "7", country: "🇺🇸", image: "images/US Queens/SaharaDavenportS2CastMug.webp" },
"Morgan McMichaels": { season: "2", placement: "8", country: "🇺🇸", image: "images/US Queens/MorganMcMichaelsS2CastMug.webp" },
"Kylie Sonique Love": { season: "2", placement: "9", country: "🇺🇸", image: "images/US Queens/SoniqueS2CastMug.webp" },
"Mystique Summers Madison": { season: "2", placement: "10", country: "🇺🇸", image: "images/US Queens/MystiqueSummersMadisonS2CastMug.webp" },
"Nicole Paige Brooks": { season: "2", placement: "11", country: "🇺🇸", image: "images/US Queens/NicolePaigeBrooksS2CastMug.webp" },
"Raja Gemini": { season: "3", placement: "1", country: "🇺🇸", image: "images/US Queens/RajaS3CastMug.webp" },
"Manila Luzon": { season: "3", placement: "2", country: "🇺🇸", image: "images/US Queens/ManilaLuzonS3CastMug.webp" },
"Alexis Mateo": { season: "3", placement: "3", country: "🇺🇸", image: "images/US Queens/AlexisMateoS3CastMug.webp" },
"Yara Sofia": { season: "3", placement: "4", country: "🇺🇸", image: "" },
"Carmen Carrera": { season: "3", placement: "5", country: "🇺🇸", image: "" },
"Delta Work": { season: "3", placement: "7", country: "🇺🇸", image: "" },
"Stacy Layne Matthews": { season: "3", placement: "8", country: "🇺🇸", image: "" },
"Mariah Paris Balenciaga": { season: "3", placement: "9", country: "🇺🇸", image: "" },
"India Ferrah": { season: "3", placement: "10", country: "🇺🇸", image: "" },
"Mimi Imfurst": { season: "3", placement: "11", country: "🇺🇸", image: "" },
"Phoenix": { season: "3", placement: "12", country: "🇺🇸", image: "" },
"Ven D-Lite": { season: "3", placement: "13", country: "🇺🇸", image: "" },
"Chad Michaels": { season: "4", placement: "2/3", country: "🇺🇸", image: "" },
"Phi Phi O'Hara": { season: "4", placement: "2/3", country: "🇺🇸", image: "" },
"Latrice Royale": { season: "4", placement: "4", country: "🇺🇸", image: "" },
"Kenya Michaels": { season: "4", placement: "5", country: "🇺🇸", image: "" },
"Dida Ritz": { season: "4", placement: "6", country: "🇺🇸", image: "" },
"Willam": { season: "4", placement: "7", country: "🇺🇸", image: "" },
"Jiggly Caliente": { season: "4", placement: "8", country: "🇺🇸", image: "" },
"Milan": { season: "4", placement: "9", country: "🇺🇸", image: "" },
"Madame LaQueer": { season: "4", placement: "10", country: "🇺🇸", image: "" },
"The Princess": { season: "4", placement: "11", country: "🇺🇸", image: "" },
"Lashauwn Beyond": { season: "4", placement: "12", country: "🇺🇸", image: "" },
"Alisa Summers": { season: "4", placement: "13", country: "🇺🇸", image: "" },
"Jinkx Monsoon": { season: "5", placement: "1", country: "🇺🇸", image: "" },
"Alaska": { season: "5", placement: "2", country: "🇺🇸", image: "images/US Queens/AlaskaS5CastMug.webp" },
"Roxxxy Andrews": { season: "5", placement: "3", country: "🇺🇸", image: "" },
"Detox": { season: "5", placement: "4", country: "🇺🇸", image: "" },
"Coco Montrese": { season: "5", placement: "5", country: "🇺🇸", image: "" },
"Alyssa Edwards": { season: "5", placement: "6", country: "🇺🇸", image: "" },
"Ivy Winters": { season: "5", placement: "7", country: "🇺🇸", image: "" },
"Jade Jolie": { season: "5", placement: "8", country: "🇺🇸", image: "" },
"Lineysha Sparx": { season: "5", placement: "9", country: "🇺🇸", image: "" },
"Honey Mahoganey": { season: "5", placement: "10/11", country: "🇺🇸", image: "" },
"Vivienne Pinay": { season: "5", placement: "10/11", country: "🇺🇸", image: "" },
"Monica Beverly Hillz": { season: "5", placement: "12", country: "🇺🇸", image: "" },
"Serena ChaCha": { season: "5", placement: "13", country: "🇺🇸", image: "" },
"Penny Tration": { season: "5", placement: "14", country: "🇺🇸", image: "" },
"Bianca Del Rio": { season: "6", placement: "1", country: "🇺🇸", image: "" },
"Adore Delano": { season: "6", placement: "2", country: "🇺🇸", image: "images/US Queens/AdoreDelanoS6CastMug.webp" },
"Courtney Act": { season: "6", placement: "3", country: "🇺🇸", image: "" },
"Darienne Lake": { season: "6", placement: "4", country: "🇺🇸", image: "" },
"BenDeLaCreme": { season: "6", placement: "5", country: "🇺🇸", image: "" },
"Joslyn Fox": { season: "6", placement: "6", country: "🇺🇸", image: "" },
"Trinity K. Bonet": { season: "6", placement: "7", country: "🇺🇸", image: "" },
"Laganja Estranja": { season: "6", placement: "8", country: "🇺🇸", image: "" },
"Milk": { season: "6", placement: "9", country: "🇺🇸", image: "" },
"Gia Gunn": { season: "6", placement: "10", country: "🇺🇸", image: "" },
"April Carrión": { season: "6", placement: "11", country: "🇺🇸", image: "" },
"Vivacio": { season: "6", placement: "12", country: "🇺🇸", image: "" },
"Magnolia Crawford": { season: "6", placement: "13", country: "🇺🇸", image: "" },
"Kelly Mantle": { season: "6", placement: "14", country: "🇺🇸", image: "" },
"Violet Chachki": { season: "7", placement: "1", country: "🇺🇸", image: "" },
"Ginger Minj": { season: "7", placement: "2/3", country: "🇺🇸", image: "" },
"Pearl": { season: "7", placement: "2/3", country: "🇺🇸", image: "" },
"Kennedy Davenport": { season: "7", placement: "4", country: "🇺🇸", image: "" },
"Katya": { season: "7", placement: "5", country: "🇺🇸", image: "" },
"Trixie Mattel": { season: "7", placement: "6", country: "🇺🇸", image: "" },
"Miss Fame": { season: "7", placement: "7", country: "🇺🇸", image: "" },
"Jaidynn Diore Fierce": { season: "7", placement: "8", country: "🇺🇸", image: "" },
"Max": { season: "7", placement: "9", country: "🇺🇸", image: "" },
"Kandy Ho": { season: "7", placement: "10", country: "🇺🇸", image: "" },
"Mrs. Kasha Davis": { season: "7", placement: "11", country: "🇺🇸", image: "" },
"Jasmine Masters": { season: "7", placement: "12", country: "🇺🇸", image: "" },
"Sasha Belle": { season: "7", placement: "13", country: "🇺🇸", image: "" },
"Tempest DuJour": { season: "7", placement: "14", country: "🇺🇸", image: "" },
"Bob The Drag Queen": { season: "8", placement: "1", country: "🇺🇸", image: "" },
"Kim Chi": { season: "8", placement: "2/3", country: "🇺🇸", image: "" },
"Naomi Smalls": { season: "8", placement: "2/3", country: "🇺🇸", image: "" },
"Chi Chi Devayne": { season: "8", placement: "4", country: "🇺🇸", image: "" },
"Derrick Barry": { season: "8", placement: "5", country: "🇺🇸", image: "" },
"Thorgy Thor": { season: "8", placement: "6", country: "🇺🇸", image: "" },
"Robbie Turner": { season: "8", placement: "7", country: "🇺🇸", image: "" },
"Acid Betty": { season: "8", placement: "8", country: "🇺🇸", image: "images/US Queens/AcidBettyS8CastMug.webp" },
"Naysha Lopez": { season: "8", placement: "9", country: "🇺🇸", image: "" },
"Cynthia Lee Fontaine": { season: "8/9", placement: "10", country: "🇺🇸", image: "" },
"Dax ExclamationPoint": { season: "8", placement: "11/12", country: "🇺🇸", image: "" },
"Laila McQueen": { season: "8", placement: "11/12", country: "🇺🇸", image: "" },
"Sasha Velour": { season: "9", placement: "1", country: "🇺🇸", image: "" },
"Peppermint": { season: "9", placement: "2", country: "🇺🇸", image: "" },
"Shea Couleé": { season: "9", placement: "3/4", country: "🇺🇸", image: "" },
"Trinity The Tuck": { season: "9", placement: "3/4", country: "🇺🇸", image: "" },
"Alexis Michelle": { season: "9", placement: "5", country: "🇺🇸", image: "" },
"Nina Bo'Nina Brown": { season: "9", placement: "6", country: "🇺🇸", image: "" },
"Valentina": { season: "9", placement: "7", country: "🇺🇸", image: "" },
"Farrah Moan": { season: "9", placement: "8", country: "🇺🇸", image: "" },
"Aja": { season: "9", placement: "9", country: "🇺🇸", image: "images/US Queens/AjaS9CastMug.webp" },
"Eureka O'Hara": { season: "9/10", placement: "11/2/3", country: "🇺🇸", image: "" },
"Charlie Hides": { season: "9", placement: "12", country: "🇺🇸", image: "" },
"Kimora Blac": { season: "9", placement: "13", country: "🇺🇸", image: "" },
"Jaymes Mansfield": { season: "9", placement: "14", country: "🇺🇸", image: "" },
"Aquaria": { season: "10", placement: "1", country: "🇺🇸", image: "" },
"Kameron Michaels": { season: "10", placement: "2/3", country: "🇺🇸", image: "" },
"Asia O'Hara": { season: "10", placement: "4", country: "🇺🇸", image: "" },
"Miz Cracker": { season: "10", placement: "5", country: "🇺🇸", image: "" },
"Monet X Change": { season: "10", placement: "6", country: "🇺🇸", image: "" },
"The Vixen": { season: "10", placement: "7", country: "🇺🇸", image: "" },
"Mo Heart": { season: "10", placement: "8", country: "🇺🇸", image: "" },
"Blair St. Clair": { season: "10", placement: "9", country: "🇺🇸", image: "" },
"Mayhem Miller": { season: "10", placement: "10", country: "🇺🇸", image: "" },
"Dty Ray Bottoms": { season: "10", placement: "11", country: "🇺🇸", image: "" },
"Yuhua Hamasaki": { season: "10", placement: "12", country: "🇺🇸", image: "" },
"Kalorie Karbdashian-Williams": { season: "10", placement: "13", country: "🇺🇸", image: "" },
"Vanessa Vanjie Mateo": { season: "10/11", placement: "14/5", country: "🇺🇸", image: "" },
"Yvie Oddly": { season: "11", placement: "1", country: "🇺🇸", image: "" },
"Brooke Lynn Hytes": { season: "11", placement: "2", country: "🇺🇸", image: "" },
"A'keria C. Davenport": { season: "11", placement: "3/4", country: "🇺🇸", image: "images/US Queens/A%27keriaCDavenportS11CastMug.webp" },
"Silky Nutmeg Ganache": { season: "11", placement: "3/4", country: "🇺🇸", image: "" },
"Nina West": { season: "11", placement: "5", country: "🇺🇸", image: "" },
"Shuga Cain": { season: "11", placement: "6", country: "🇺🇸", image: "" },
"Plastique Tiara": { season: "11", placement: "7", country: "🇺🇸", image: "" },
"Ra'Jah O'Hara": { season: "11", placement: "8", country: "🇺🇸", image: "" },
"Scarlet Envy": { season: "11", placement: "9", country: "🇺🇸", image: "" },
"Ariel Versace": { season: "11", placement: "10", country: "🇺🇸", image: "" },
"Mercedes Iman Diamond": { season: "11", placement: "11", country: "🇺🇸", image: "" },
"Honey Davenport": { season: "11", placement: "12", country: "🇺🇸", image: "" },
"Kahanna Montrese": { season: "11", placement: "13", country: "🇺🇸", image: "" },
"Jaida Essence Hall": { season: "12", placement: "1", country: "🇺🇸", image: "" },
"Crystal Methyd": { season: "12", placement: "2/3", country: "🇺🇸", image: "" },
"Gigi Goode": { season: "12", placement: "2/3", country: "🇺🇸", image: "" },
"Jackie Cox": { season: "12", placement: "5", country: "🇺🇸", image: "" },
"Heidi N' Closet": { season: "12", placement: "6", country: "🇺🇸", image: "" },
"Widow Von'Du": { season: "12", placement: "7", country: "🇺🇸", image: "" },
"Jan": { season: "12", placement: "8", country: "🇺🇸", image: "" },
"Brita Filter": { season: "12", placement: "9", country: "🇺🇸", image: "" },
"Aiden Zhane": { season: "12", placement: "10", country: "🇺🇸", image: "images/US Queens/AidenZhaneS12CastMug.webp" },
"Nicky Doll": { season: "12", placement: "11", country: "🇺🇸", image: "" },
"Rock M. Sakura": { season: "12", placement: "12", country: "🇺🇸", image: "" },
"Dahlia Sin": { season: "12", placement: "13", country: "🇺🇸", image: "" },
"Symone": { season: "13", placement: "1", country: "🇺🇸", image: "" },
"Kandy Me": { season: "13", placement: "2", country: "🇺🇸", image: "" },
"Gottmik": { season: "13", placement: "3/4", country: "🇺🇸", image: "" },
"Rosé": { season: "13", placement: "3/4", country: "🇺🇸", image: "" },
"Olivia Lux": { season: "13", placement: "5", country: "🇺🇸", image: "" },
"Utica Queen": { season: "13", placement: "6", country: "🇺🇸", image: "" },
"Tina Burner": { season: "13", placement: "7", country: "🇺🇸", image: "" },
"Denali": { season: "13", placement: "8", country: "🇺🇸", image: "" },
"LaLa Ri": { season: "13", placement: "10", country: "🇺🇸", image: "" },
"Tamisha Iman": { season: "13", placement: "11", country: "🇺🇸", image: "" },
"Joey Jay": { season: "13", placement: "12", country: "🇺🇸", image: "" },
"Kahmora Hall": { season: "13", placement: "13", country: "🇺🇸", image: "" },
"Willow Pill": { season: "14", placement: "1", country: "🇺🇸", image: "" },
"Lady Camden": { season: "14", placement: "2", country: "🇺🇸", image: "" },
"Angeria Paris VanMicheals": { season: "14", placement: "3/4/5", country: "🇺🇸", image: "" },
"Bosco": { season: "14", placement: "3/4/5", country: "🇺🇸", image: "" },
"Daya Betty": { season: "14", placement: "3/4/5", country: "🇺🇸", image: "" },
"Deja Skye": { season: "14", placement: "6/7", country: "🇺🇸", image: "" },
"Jorgeo": { season: "14", placement: "6/7", country: "🇺🇸", image: "" },
"Jasmine Kennedie": { season: "14", placement: "8", country: "🇺🇸", image: "" },
"Kerri Colby": { season: "14", placement: "9", country: "🇺🇸", image: "" },
"Maddy Morphosis": { season: "14", placement: "10", country: "🇺🇸", image: "" },
"Orion Story": { season: "14", placement: "11", country: "🇺🇸", image: "" },
"Kornbread Jeté": { season: "14", placement: "12", country: "🇺🇸", image: "" },
"Alyssa Hunter": { season: "14", placement: "13", country: "🇺🇸", image: "" },
"June Jumbalaya": { season: "14", placement: "14", country: "🇺🇸", image: "" },
"Sasha Colby": { season: "15", placement: "1", country: "🇺🇸", image: "" },
"Anetra": { season: "15", placement: "2", country: "🇺🇸", image: "" },
"Luxx Noir London": { season: "15", placement: "3/4", country: "🇺🇸", image: "" },
"Mistress Isabelle Brooks": { season: "15", placement: "3/4", country: "🇺🇸", image: "" },
"Loosey LaDuca": { season: "15", placement: "5", country: "🇺🇸", image: "" },
"Salina Estitties": { season: "15", placement: "6", country: "🇺🇸", image: "" },
"Marcia Marcia Marcia": { season: "15", placement: "7", country: "🇺🇸", image: "" },
"Malaysia Babydoll Foxx": { season: "15", placement: "8", country: "🇺🇸", image: "" },
"Spice": { season: "15", placement: "9", country: "🇺🇸", image: "" },
"Jax": { season: "15", placement: "10", country: "🇺🇸", image: "" },
"Aura Mayari": { season: "15", placement: "11", country: "🇺🇸", image: "" },
"Robin Fierce": { season: "15", placement: "12", country: "🇺🇸", image: "" },
"Amethyst": { season: "15", placement: "13", country: "🇺🇸", image: "" },
"Sugar": { season: "15", placement: "14", country: "🇺🇸", image: "" },
"Princess Poppy": { season: "15", placement: "15", country: "🇺🇸", image: "" },
"Irene The Alien": { season: "15", placement: "16", country: "🇺🇸", image: "" },
"Nymphia Wind": { season: "16", placement: "1", country: "🇺🇸", image: "" },
"Sapphira Cristál": { season: "16", placement: "2", country: "🇺🇸", image: "" },
"Plane Jane": { season: "16", placement: "3/4", country: "🇺🇸", image: "" },
"Q": { season: "16", placement: "3/4", country: "🇺🇸", image: "" },
"Morphine Love Dion": { season: "15", placement: "5", country: "🇺🇸", image: "" },
"Dawn": { season: "16", placement: "6", country: "🇺🇸", image: "" },
"Mhi'ya Iman Le'Paige": { season: "16", placement: "7", country: "🇺🇸", image: "" },
"Plasma": { season: "16", placement: "8", country: "🇺🇸", image: "" },
"Xunami Me": { season: "16", placement: "9", country: "🇺🇸", image: "" },
"Megami": { season: "16", placement: "10", country: "🇺🇸", image: "" },
"Geneva Karr": { season: "16", placement: "11", country: "🇺🇸", image: "" },
"Amanda Tori Meating": { season: "16", placement: "12", country: "🇺🇸", image: "" },
"Mirage": { season: "16", placement: "13", country: "🇺🇸", image: "" },
"Hershii LiqCour-Jeté": { season: "16", placement: "14", country: "🇺🇸", image: "" },
"Onya Nurve": { season: "17", placement: "1", country: "🇺🇸", image: "" },
"Jewels Sparkles": { season: "17", placement: "2", country: "🇺🇸", image: "" },
"Lexi Love": { season: "17", placement: "3/4", country: "🇺🇸", image: "" },
"Sam Star": { season: "17", placement: "3/4", country: "🇺🇸", image: "" },
"Suzie Toot": { season: "17", placement: "5", country: "🇺🇸", image: "" },
"Lana Ja'Rae": { season: "17", placement: "6", country: "🇺🇸", image: "" }, 
"Lydia B. Kollins": { season: "17", placement: "7", country: "🇺🇸", image: "" },
"Arrietty": { season: "17", placement: "8", country: "🇺🇸", image: "" },
"Kori King": { season: "17", placement: "9", country: "🇺🇸", image: "" },
"Acacia Forgot": { season: "17", placement: "10", country: "🇺🇸", image: "images/US Queens/AcaciaForgotS17CastMug.webp" },
"Crystal Envy": { season: "17", placement: "11", country: "🇺🇸", image: "" },
"Hormona Lisa": { season: "17", placement: "12", country: "🇺🇸", image: "" },
"Joella": { season: "17", placement: "13", country: "🇺🇸", image: "" },
"Lucky Starzzz": { season: "17", placement: "14", country: "🇺🇸", image: "" },
"The Vivienne": { season: "1", placement: "1", country: "🇬🇧", image: "" },
"Divina De Campo": { season: "1", placement: "2", country: "🇬🇧", image: "" },
"Baga Chipz": { season: "1", placement: "3", country: "🇬🇧", image: "" },
"Cheryl": { season: "1", placement: "4", country: "🇬🇧", image: "" },
"Blu Hydrangea": { season: "1", placement: "5", country: "🇬🇧", image: "" },
"Crystal": { season: "1", placement: "6", country: "🇬🇧", image: "" },
"Sum Ting Wong": { season: "1", placement: "7", country: "🇬🇧", image: "" },
"Vinegar Strokes": { season: "1", placement: "8", country: "🇬🇧", image: "" },
"Scaredy Kat": { season: "1", placement: "9", country: "🇬🇧", image: "" },
"Gothy Kendoll": { season: "1", placement: "10", country: "🇬🇧", image: "" },
"Lawrence Chaney": { season: "2", placement: "1", country: "🇬🇧", image: "" },
"Bimini Bon-Boulash": { season: "2", placement: "2/3", country: "🇬🇧", image: "" },
"Tayce": { season: "2", placement: "2/3", country: "🇬🇧", image: "" },
"Ellie Diamond": { season: "2", placement: "4", country: "🇬🇧", image: "" },
"A'Whora": { season: "2", placement: "5", country: "🇬🇧", image: "" },
"Sister Sister": { season: "2", placement: "6", country: "🇬🇧", image: "" },
"Tia Kofi": { season: "2", placement: "7", country: "🇬🇧", image: "" },
"Joe Black": { season: "2", placement: "8", country: "🇬🇧", image: "" },
"Veronica Green": { season: "2/3", placement: "9", country: "🇬🇧", image: "" },
"Ginny Lemon": { season: "2", placement: "10", country: "🇬🇧", image: "" },
"Asttina Mandella": { season: "2", placement: "11", country: "🇬🇧", image: "" },
"Cherry Valentine": { season: "2", placement: "12", country: "🇬🇧", image: "" },
"Krystal Versace": { season: "3", placement: "1", country: "🇬🇧", image: "" },
"Ella Vaday": { season: "3", placement: "2/3", country: "🇬🇧", image: "" },
"Kitty Scott-Cla": { season: "3", placement: "2/3", country: "🇬🇧", image: "" },
"Vanity Milan": { season: "3", placement: "4", country: "🇬🇧", image: "" },
"Scarlett Harlett": { season: "3", placement: "5", country: "🇬🇧", image: "" },
"Choriza May": { season: "3", placement: "6/7", country: "🇬🇧", image: "" },
"River Medway": { season: "3", placement: "6/7", country: "🇬🇧", image: "" },
"Charity Kase": { season: "3", placement: "8", country: "🇬🇧", image: "" },
"Victoria Scone": { season: "3", placement: "10", country: "🇬🇧", image: "" },
"Elektra Fence": { season: "3", placement: "11", country: "🇬🇧", image: "" },
"Anubis": { season: "3", placement: "12", country: "🇬🇧", image: "" },
"Danny Beard": { season: "4", placement: "1", country: "🇬🇧", image: "" },
"Cheddar Gorgeo": { season: "4", placement: "2", country: "🇬🇧", image: "" },
"Black Peppa": { season: "4", placement: "3/4", country: "🇬🇧", image: "" },
"Jonbers Blonde": { season: "4", placement: "3/4", country: "🇬🇧", image: "" },
"Pixie Polite": { season: "4", placement: "5", country: "🇬🇧", image: "" },
"Dakota Schiffer": { season: "4", placement: "6", country: "🇬🇧", image: "" },
"Le Fil": { season: "4", placement: "7", country: "🇬🇧", image: "" },
"Baby": { season: "4", placement: "8", country: "🇬🇧", image: "" },
"Sminty Drop": { season: "4", placement: "9", country: "🇬🇧", image: "" },
"Copper Topp": { season: "4", placement: "10", country: "🇬🇧", image: "" },
"Starlet": { season: "4", placement: "11", country: "🇬🇧", image: "" },
"Jt May": { season: "4", placement: "12", country: "🇬🇧", image: "" },
"Ginger Johnson": { season: "5", placement: "1", country: "🇬🇧", image: "" },
"Michael Marouli": { season: "5", placement: "2", country: "🇬🇧", image: "" },
"Tomara Thomas": { season: "5", placement: "3", country: "🇬🇧", image: "" },
"DeDeLicio": { season: "5", placement: "4", country: "🇬🇧", image: "" },
"Kate Butch": { season: "5", placement: "5", country: "🇬🇧", image: "" },
"Cara Melle": { season: "5", placement: "6", country: "🇬🇧", image: "" },
"Vicki Vivacio": { season: "5", placement: "7", country: "🇬🇧", image: "" },
"Banksie": { season: "5", placement: "8", country: "🇬🇧", image: "" },
"Miss Naomi": { season: "5", placement: "9", country: "🇬🇧", image: "" },
"Alexis Saint-Pete": { season: "5", placement: "10", country: "🇬🇧", image: "" },
"Kyran Thrax": { season: "6", placement: "1", country: "🇬🇧", image: "" },
"La Voix": { season: "6", placement: "2", country: "🇬🇧", image: "" },
"Marmalade": { season: "6", placement: "3/4", country: "🇬🇧", image: "" },
"Rileasa": { season: "6", placement: "3/4", country: "🇬🇧", image: "" },
"Lill": { season: "6", placement: "5", country: "🇬🇧", image: "" },
"Charra Tea": { season: "6", placement: "6", country: "🇬🇧", image: "" },
"Actavia": { season: "6", placement: "7", country: "🇬🇧", image: "" },
"Chanel O'Conor": { season: "6", placement: "8", country: "🇬🇧", image: "" },
"Kiki Snatch": { season: "6", placement: "9", country: "🇬🇧", image: "" },
"Zahirah Zapanta": { season: "6", placement: "10", country: "🇬🇧", image: "" },
"Dita Garbo": { season: "6", placement: "11", country: "🇬🇧", image: "" },
"Saki Yew": { season: "6", placement: "12", country: "🇬🇧", image: "" },
"Priyanka": { season: "1", placement: "1", country: "🇨🇦", image: "" },
"Rita Baga": { season: "1", placement: "2/3", country: "🇨🇦", image: "" },
"Scarlett BoBo": { season: "1", placement: "2/3", country: "🇨🇦", image: "" },
"Jimbo": { season: "1", placement: "4", country: "🇨🇦", image: "" },
"Lemon": { season: "1", placement: "5", country: "🇨🇦", image: "" },
"Ilona Verley": { season: "1", placement: "6", country: "🇨🇦", image: "" },
"BOA": { season: "1", placement: "7", country: "🇨🇦", image: "" },
"Kiara": { season: "1", placement: "8", country: "🇨🇦", image: "" },
"Tynomi Banks": { season: "1", placement: "9", country: "🇨🇦", image: "" },
"Anastarzia Anaquway": { season: "1", placement: "10", country: "🇨🇦", image: "" },
"Kyne": { season: "1", placement: "11", country: "🇨🇦", image: "" },
"Juice Boxx": { season: "1", placement: "12", country: "🇨🇦", image: "" },
"Icesis Couture": { season: "2", placement: "1", country: "🇨🇦", image: "" },
"Kendall Gender": { season: "2", placement: "2/3", country: "🇨🇦", image: "" },
"Pythia": { season: "2", placement: "2/3", country: "🇨🇦", image: "" },
"Gia Metric": { season: "2", placement: "4", country: "🇨🇦", image: "" },
"Adriana": { season: "2", placement: "5", country: "🇨🇦", image: "" },
"Kimora Amour": { season: "2", placement: "6", country: "🇨🇦", image: "" },
"Synthia Kiss": { season: "2", placement: "7", country: "🇨🇦", image: "" },
"Eve 6000": { season: "2", placement: "8", country: "🇨🇦", image: "" },
"Suki Doll": { season: "2", placement: "9", country: "🇨🇦", image: "" },
"Stephanie Prince": { season: "2", placement: "10", country: "🇨🇦", image: "" },
"Océane Aqua-Black": { season: "2", placement: "11", country: "🇨🇦", image: "" },
"Beth": { season: "2", placement: "12", country: "🇨🇦", image: "" },
"Giséle Lullaby": { season: "3", placement: "1", country: "🇨🇦", image: "" },
"Jada Shada Hudson": { season: "3", placement: "2", country: "🇨🇦", image: "" },
"Kimmy Couture": { season: "3", placement: "3/4", country: "🇨🇦", image: "" },
"Miss Fiercalicio": { season: "3", placement: "3/4", country: "🇨🇦", image: "" },
"Vivian Vanderps": { season: "3", placement: "5", country: "🇨🇦", image: "" },
"Irma Gerd": { season: "3", placement: "6", country: "🇨🇦", image: "" },
"Bombae": { season: "3", placement: "7", country: "🇨🇦", image: "" },
"Lady Boom Boom": { season: "3", placement: "8", country: "🇨🇦", image: "" },
"Kaos": { season: "3", placement: "9", country: "🇨🇦", image: "" },
"Chelazon Leroux": { season: "3", placement: "10", country: "🇨🇦", image: "" },
"Miss Moço": { season: "3", placement: "11", country: "🇨🇦", image: "" },
"Halal Bae": { season: "3", placement: "12", country: "🇨🇦", image: "" },
"Ven": { season: "4", placement: "1", country: "🇨🇦", image: "" },
"Aurora Matrix": { season: "4", placement: "2", country: "🇨🇦", image: "" },
"Denim": { season: "4", placement: "3/4", country: "🇨🇦", image: "" },
"Nearah Nuff": { season: "4", placement: "3/4", country: "🇨🇦", image: "" },
"Melinda Verga": { season: "4", placement: "5", country: "🇨🇦", image: "" },
"Kiki Coe": { season: "4", placement: "6", country: "🇨🇦", image: "" },
"Aimee Yonce Shennel": { season: "4", placement: "7", country: "🇨🇦", image: "" },
"Kitten Kaboodle": { season: "4", placement: "8", country: "🇨🇦", image: "" },
"Luna DuBois": { season: "4", placement: "9", country: "🇨🇦", image: "" },
"The Girlfriend Experience": { season: "4", placement: "10", country: "🇨🇦", image: "" },
"Sisi Superstar": { season: "4", placement: "11", country: "🇨🇦", image: "" },
"The Virgo Queen": { season: "5", placement: "1", country: "🇨🇦", image: "" },
"Makayla Couture": { season: "5", placement: "2", country: "🇨🇦", image: "" },
"Helena Poison": { season: "5", placement: "3/4", country: "🇨🇦", image: "" },
"Minhi Wang": { season: "5", placement: "3/4", country: "🇨🇦", image: "" },
"Perla": { season: "5", placement: "5", country: "🇨🇦", image: "" },
"Xana": { season: "5", placement: "6", country: "🇨🇦", image: "" },
"Uma Gahd": { season: "5", placement: "7", country: "🇨🇦", image: "" },
"Jaylene Tyme": { season: "5", placement: "8", country: "🇨🇦", image: "" },
"Sanjina Dabish Queen": { season: "5", placement: "9", country: "🇨🇦", image: "" },
"Tiffany Ann Co.": { season: "5", placement: "10", country: "🇨🇦", image: "" },
"Tara Nova": { season: "5", placement: "11", country: "🇨🇦", image: "" },
"Kita Mean": { season: "1", placement: "1", country: "🇦🇺", image: "" },
"Art Simone": { season: "1", placement: "2", country: "🇦🇺", image: "" },
"Karen From Finance": { season: "1", placement: "3/4", country: "🇦🇺", image: "" },
"Elektra Shock": { season: "1", placement: "5", country: "🇦🇺", image: "" },
"Maxi Shield": { season: "1", placement: "6", country: "🇦🇺", image: "" },
"Etcetera Etcetera": { season: "1", placement: "7", country: "🇦🇺", image: "" },
"Anita Wigl'it": { season: "1", placement: "8", country: "🇦🇺", image: "" },
"Coco Jumbo": { season: "1", placement: "9", country: "🇦🇺", image: "" },
"Jojo Zaho": { season: "1", placement: "10", country: "🇦🇺", image: "" },
"Spankie Jackzon": { season: "2", placement: "1", country: "🇦🇺", image: "" },
"Hannah Conda": { season: "2", placement: "2/3", country: "🇦🇺", image: "" },
"Kween Kong": { season: "2", placement: "2/3", country: "🇦🇺", image: "" },
"Molly Poppinz": { season: "2", placement: "4", country: "🇦🇺", image: "" },
"Beverly Kills": { season: "2", placement: "5", country: "🇦🇺", image: "" },
"Yuri Guaii": { season: "2", placement: "6", country: "🇦🇺", image: "" },
"Minnie Cooper": { season: "2", placement: "7", country: "🇦🇺", image: "" },
"Pomara Fifth": { season: "2", placement: "8", country: "🇦🇺", image: "" },
"Aubrey Haive": { season: "2", placement: "9", country: "🇦🇺", image: "" },
"Faúx Fúr": { season: "2", placement: "10", country: "🇦🇺", image: "" },
"Isis Avis Loren": { season: "3", placement: "1", country: "🇦🇺", image: "" },
"Gabriella Labucci": { season: "3", placement: "2", country: "🇦🇺", image: "" },
"Flor": { season: "3", placement: "3", country: "🇦🇺", image: "" },
"Hollywould Star": { season: "3", placement: "4", country: "🇦🇺", image: "" },
"Bumpa Love": { season: "3", placement: "5", country: "🇦🇺", image: "" },
"Ashley Madison": { season: "3", placement: "6", country: "🇦🇺", image: "" },
"Rita Menu": { season: "3", placement: "7", country: "🇦🇺", image: "" },
"Ivanna Drink": { season: "3", placement: "8", country: "🇦🇺", image: "" },
"Ivory Glaze": { season: "3", placement: "9", country: "🇦🇺", image: "" },
"Amyl": { season: "3", placement: "10", country: "🇦🇺", image: "" },
"Lazy San": { season: "4", placement: "1", country: "🇦🇺", image: "" },
"Mandy Moobs": { season: "4", placement: "2/3", country: "🇦🇺", image: "" },
"Vybe": { season: "4", placement: "2/3", country: "🇦🇺", image: "" },
"Freya Armani": { season: "4", placement: "4", country: "🇦🇺", image: "" },
"Nikita Iman": { season: "4", placement: "5", country: "🇦🇺", image: "" },
"Max Drag Queen": { season: "4", placement: "6", country: "🇦🇺", image: "" },
"Brenda Bressed": { season: "4", placement: "7", country: "🇦🇺", image: "" },
"Lucina Innocence": { season: "4", placement: "8", country: "🇦🇺", image: "" },
"Karna Ford": { season: "4", placement: "9", country: "🇦🇺", image: "" },
"Olivia Dreams": { season: "4", placement: "10", country: "🇦🇺", image: "" },
 };
