window.queens = {
"Bebe Zahara Benet": { season: "US1", placement: "1", country: "🇺🇸", image: "" },
"Nina Flowers": { season: "US1", placement: "2", country: "🇺🇸", image: "" },
"Rebecca Glasscock": { season: "US1", placement: "3", country: "🇺🇸", image: "" },
"Shannel": { season: "US1", placement: "4", country: "🇺🇸", image: "" },
"Ongina": { season: "US1", placement: "5", country: "🇺🇸", image: "" },
"Jade": { season: "US1", placement: "6", country: "🇺🇸", image: "" },
"Akashia": { season: "US1", placement: "7", country: "🇺🇸", image: "" },
"Tammie Brown": { season: "US1", placement: "8", country: "🇺🇸", image: "" },
"Victoria Porkchop Parker": { season: "US1", placement: "9", country: "🇺🇸", image: "" },
"Raven": { season: "US2", placement: "2", country: "🇺🇸", image: "" },
"Jujubee": { season: "US2", placement: "3", country: "🇺🇸", image: "" },
"Tatianna": { season: "US2", placement: "4", country: "🇺🇸", image: "" },
"Pandora Boxx": { season: "US2", placement: "5", country: "🇺🇸", image: "" },
"Jessica Wild": { season: "US2", placement: "6", country: "🇺🇸", image: "" },
"Sahara Davenport": { season: "US2", placement: "7", country: "🇺🇸", image: "" },
"Morgan McMichaels": { season: "US2", placement: "8", country: "🇺🇸", image: "" },
"Kylie Sonique Love": { season: "US2", placement: "9", country: "🇺🇸", image: "" },
"Mystique Summers Madison": { season: "US2", placement: "10", country: "🇺🇸", image: "" },
"Nicole Paige Brooks": { season: "US2", placement: "11", country: "🇺🇸", image: "" },
"Raja Gemini": { season: "US3", placement: "1", country: "🇺🇸", image: "" },
"Manila Luzon": { season: "US3", placement: "2", country: "🇺🇸", image: "" },
"Alexis Mateo": { season: "US3", placement: "3", country: "🇺🇸", image: "" },
"Yara Sofia": { season: "US3", placement: "4", country: "🇺🇸", image: "" },
"Carmen Carrera": { season: "US3", placement: "5", country: "🇺🇸", image: "" },
"Delta Work": { season: "US3", placement: "7", country: "🇺🇸", image: "" },
"Stacy Layne Matthews": { season: "US3", placement: "8", country: "🇺🇸", image: "" },
"Mariah Paris Balenciaga": { season: "US3", placement: "9", country: "🇺🇸", image: "" },
"India Ferrah": { season: "US3", placement: "10", country: "🇺🇸", image: "" },
"Mimi Imfurst": { season: "US3", placement: "11", country: "🇺🇸", image: "" },
"Phoenix": { season: "US3", placement: "12", country: "🇺🇸", image: "" },
"Venus D-Lite": { season: "US3", placement: "13", country: "🇺🇸", image: "" },
"Chad Michaels": { season: "US4", placement: "2/3", country: "🇺🇸", image: "" },
"Phi Phi O'Hara": { season: "US4", placement: "2/3", country: "🇺🇸", image: "" },
"Latrice Royale": { season: "US4", placement: "4", country: "🇺🇸", image: "" },
"Kenya Michaels": { season: "US4", placement: "5", country: "🇺🇸", image: "" },
"Dida Ritz": { season: "US4", placement: "6", country: "🇺🇸", image: "" },
"Willam": { season: "US4", placement: "7", country: "🇺🇸", image: "" },
"Jiggly Caliente": { season: "US4", placement: "8", country: "🇺🇸", image: "" },
"Milan": { season: "US4", placement: "9", country: "🇺🇸", image: "" },
"Madame LaQueer": { season: "US4", placement: "10", country: "🇺🇸", image: "" },
"The Princess": { season: "US4", placement: "11", country: "🇺🇸", image: "" },
"Lashauwn Beyond": { season: "US4", placement: "12", country: "🇺🇸", image: "" },
"Alisa Summers": { season: "US4", placement: "13", country: "🇺🇸", image: "" },
"Jinkx Monsoon": { season: "US5", placement: "1", country: "🇺🇸", image: "" },
"Alaska": { season: "US5", placement: "2", country: "🇺🇸", image: "" },
"Roxxxy Andrews": { season: "US5", placement: "3", country: "🇺🇸", image: "" },
"Detox": { season: "US5", placement: "4", country: "🇺🇸", image: "" },
"Coco Montrese": { season: "US5", placement: "5", country: "🇺🇸", image: "" },
"Alyssa Edwards": { season: "US5", placement: "6", country: "🇺🇸", image: "" },
"Ivy Winters": { season: "US5", placement: "7", country: "🇺🇸", image: "" },
"Jade Jolie": { season: "US5", placement: "8", country: "🇺🇸", image: "" },
"Lineysha Sparx": { season: "US5", placement: "9", country: "🇺🇸", image: "" },
"Honey Mahoganey": { season: "US5", placement: "10/11", country: "🇺🇸", image: "" },
"Vivienne Pinay": { season: "US5", placement: "10/11", country: "🇺🇸", image: "" },
"Monica Beverly Hillz": { season: "US5", placement: "12", country: "🇺🇸", image: "" },
"Serena ChaCha": { season: "US5", placement: "13", country: "🇺🇸", image: "" },
"Penny Tration": { season: "US5", placement: "14", country: "🇺🇸", image: "" },
"Bianca Del Rio": { season: "US6", placement: "1", country: "🇺🇸", image: "" },
"Adore Delano": { season: "US6", placement: "2", country: "🇺🇸", image: "" },
"Courtney Act": { season: "US6", placement: "3", country: "🇺🇸", image: "" },
"Darienne Lake": { season: "US6", placement: "4", country: "🇺🇸", image: "" },
"BenDeLaCreme": { season: "US6", placement: "5", country: "🇺🇸", image: "" },
"Joslyn Fox": { season: "US6", placement: "6", country: "🇺🇸", image: "" },
"Trinity K. Bonet": { season: "US6", placement: "7", country: "🇺🇸", image: "" },
"Laganja Estranja": { season: "US6", placement: "8", country: "🇺🇸", image: "" },
"Milk": { season: "US6", placement: "9", country: "🇺🇸", image: "" },
"Gia Gunn": { season: "US6", placement: "10", country: "🇺🇸", image: "" },
"April Carrión": { season: "US6", placement: "11", country: "🇺🇸", image: "" },
"Vivacious": { season: "US6", placement: "12", country: "🇺🇸", image: "" },
"Magnolia Crawford": { season: "US6", placement: "13", country: "🇺🇸", image: "" },
"Kelly Mantle": { season: "US6", placement: "14", country: "🇺🇸", image: "" },
"Violet Chachki": { season: "US7", placement: "1", country: "🇺🇸", image: "" },
"Ginger Minj": { season: "US7", placement: "2/3", country: "🇺🇸", image: "" },
"Pearl": { season: "US7", placement: "2/3", country: "🇺🇸", image: "" },
"Kennedy Davenport": { season: "US7", placement: "4", country: "🇺🇸", image: "" },
"Katya": { season: "US7", placement: "5", country: "🇺🇸", image: "" },
"Trixie Mattel": { season: "US7", placement: "6", country: "🇺🇸", image: "" },
"Miss Fame": { season: "US7", placement: "7", country: "🇺🇸", image: "" },
"Jaidynn Diore Fierce": { season: "US7", placement: "8", country: "🇺🇸", image: "" },
"Max": { season: "US7", placement: "9", country: "🇺🇸", image: "" },
"Kandy Ho": { season: "US7", placement: "10", country: "🇺🇸", image: "" },
"Mrs. Kasha Davis": { season: "US7", placement: "11", country: "🇺🇸", image: "" },
"Jasmine Masters": { season: "US7", placement: "12", country: "🇺🇸", image: "" },
"Sasha Belle": { season: "US7", placement: "13", country: "🇺🇸", image: "" },
"Tempest DuJour": { season: "US7", placement: "14", country: "🇺🇸", image: "" },
"Bob The Drag Queen": { season: "US8", placement: "1", country: "🇺🇸", image: "" },
"Kim Chi": { season: "US8", placement: "2/3", country: "🇺🇸", image: "" },
"Naomi Smalls": { season: "US8", placement: "2/3", country: "🇺🇸", image: "" },
"Chi Chi Devayne": { season: "US8", placement: "4", country: "🇺🇸", image: "" },
"Derrick Barry": { season: "US8", placement: "5", country: "🇺🇸", image: "" },
"Thorgy Thor": { season: "US8", placement: "6", country: "🇺🇸", image: "" },
"Robbie Turner": { season: "US8", placement: "7", country: "🇺🇸", image: "" },
"Acid Betty": { season: "US8", placement: "8", country: "🇺🇸", image: "" },
"Naysha Lopez": { season: "US8", placement: "9", country: "🇺🇸", image: "" },
"Cynthia Lee Fontaine": { season: "US8/9", placement: "10", country: "🇺🇸", image: "" },
"Dax ExclamationPoint": { season: "US8", placement: "11/12", country: "🇺🇸", image: "" },
"Laila McQueen": { season: "US8", placement: "11/12", country: "🇺🇸", image: "" },
"Sasha Velour": { season: "US9", placement: "1", country: "🇺🇸", image: "" },
"Peppermint": { season: "US9", placement: "2", country: "🇺🇸", image: "" },
"Shea Couleé": { season: "US9", placement: "3/4", country: "🇺🇸", image: "" },
"Trinity The Tuck": { season: "US9", placement: "3/4", country: "🇺🇸", image: "" },
"Alexis Michelle": { season: "US9", placement: "5", country: "🇺🇸", image: "" },
"Nina Bo'Nina Brown": { season: "US9", placement: "6", country: "🇺🇸", image: "" },
"Valentina": { season: "US9", placement: "7", country: "🇺🇸", image: "" },
"Farrah Moan": { season: "US9", placement: "8", country: "🇺🇸", image: "" },
"Aja": { season: "US9", placement: "9", country: "🇺🇸", image: "" },
"Eureka O'Hara": { season: "US9/10", placement: "11/2/3", country: "🇺🇸", image: "" },
"Charlie Hides": { season: "US9", placement: "12", country: "🇺🇸", image: "" },
"Kimora Blac": { season: "US9", placement: "13", country: "🇺🇸", image: "" },
"Jaymes Mansfield": { season: "US9", placement: "14", country: "🇺🇸", image: "" },
"Aquaria": { season: "US10", placement: "1", country: "🇺🇸", image: "" },
"Kameron Michaels": { season: "US10", placement: "2/3", country: "🇺🇸", image: "" },
"Asia O'Hara": { season: "US10", placement: "4", country: "🇺🇸", image: "" },
"Miz Cracker": { season: "US10", placement: "5", country: "🇺🇸", image: "" },
"Monet X Change": { season: "US10", placement: "6", country: "🇺🇸", image: "" },
"The Vixen": { season: "US10", placement: "7", country: "🇺🇸", image: "" },
"Mo Heart": { season: "US10", placement: "8", country: "🇺🇸", image: "" },
"Blair St. Clair": { season: "US10", placement: "9", country: "🇺🇸", image: "" },
"Mayhem Miller": { season: "US10", placement: "10", country: "🇺🇸", image: "" },
"Dusty Ray Bottoms": { season: "US10", placement: "11", country: "🇺🇸", image: "" },
"Yuhua Hamasaki": { season: "US10", placement: "12", country: "🇺🇸", image: "" },
"Kalorie Karbdashian-Williams": { season: "US10", placement: "13", country: "🇺🇸", image: "" },
"Vanessa Vanjie Mateo": { season: "US10/11", placement: "14/5", country: "🇺🇸", image: "" },
"Yvie Oddly": { season: "US11", placement: "1", country: "🇺🇸", image: "" },
"Brooke Lynn Hytes": { season: "US11", placement: "2", country: "🇺🇸", image: "" },
"A'keria C. Davenport": { season: "US11", placement: "3/4", country: "🇺🇸", image: "" },
"Silky Nutmeg Ganache": { season: "US11", placement: "3/4", country: "🇺🇸", image: "" },
"Nina West": { season: "US11", placement: "5", country: "🇺🇸", image: "" },
"Shuga Cain": { season: "US11", placement: "6", country: "🇺🇸", image: "" },
"Plastique Tiara": { season: "US11", placement: "7", country: "🇺🇸", image: "" },
"Ra'Jah O'Hara": { season: "US11", placement: "8", country: "🇺🇸", image: "" },
"Scarlet Envy": { season: "US11", placement: "9", country: "🇺🇸", image: "" },
"Ariel Versace": { season: "US11", placement: "10", country: "🇺🇸", image: "" },
"Mercedes Iman Diamond": { season: "US11", placement: "11", country: "🇺🇸", image: "" },
"Honey Davenport": { season: "US11", placement: "12", country: "🇺🇸", image: "" },
"Kahanna Montrese": { season: "US11", placement: "13", country: "🇺🇸", image: "" },
"Jaida Essence Hall": { season: "US12", placement: "1", country: "🇺🇸", image: "" },
"Crystal Methyd": { season: "US12", placement: "2/3", country: "🇺🇸", image: "" },
"Gigi Goode": { season: "US12", placement: "2/3", country: "🇺🇸", image: "" },
"Jackie Cox": { season: "US12", placement: "5", country: "🇺🇸", image: "" },
"Heidi N' Closet": { season: "US12", placement: "6", country: "🇺🇸", image: "" },
"Widow Von'Du": { season: "US12", placement: "7", country: "🇺🇸", image: "" },
"Jan": { season: "US12", placement: "8", country: "🇺🇸", image: "" },
"Brita Filter": { season: "US12", placement: "9", country: "🇺🇸", image: "" },
"Aiden Zhane": { season: "US12", placement: "10", country: "🇺🇸", image: "" },
"Nicky Doll": { season: "US12", placement: "11", country: "🇺🇸", image: "" },
"Rock M. Sakura": { season: "US12", placement: "12", country: "🇺🇸", image: "" },
"Dahlia Sin": { season: "US12", placement: "13", country: "🇺🇸", image: "" },
"Symone": { season: "US13", placement: "1", country: "🇺🇸", image: "" },
"Kandy Muse": { season: "US13", placement: "2", country: "🇺🇸", image: "" },
"Gottmik": { season: "US13", placement: "3/4", country: "🇺🇸", image: "" },
"Rosé": { season: "US13", placement: "3/4", country: "🇺🇸", image: "" },
"Olivia Lux": { season: "US13", placement: "5", country: "🇺🇸", image: "" },
"Utica Queen": { season: "US13", placement: "6", country: "🇺🇸", image: "" },
"Tina Burner": { season: "US13", placement: "7", country: "🇺🇸", image: "" },
"Denali": { season: "US13", placement: "8", country: "🇺🇸", image: "" },
"LaLa Ri": { season: "US13", placement: "10", country: "🇺🇸", image: "" },
"Tamisha Iman": { season: "US13", placement: "11", country: "🇺🇸", image: "" },
"Joey Jay": { season: "US13", placement: "12", country: "🇺🇸", image: "" },
"Kahmora Hall": { season: "US13", placement: "13", country: "🇺🇸", image: "" },
"Willow Pill": { season: "US14", placement: "1", country: "🇺🇸", image: "" },
"Lady Camden": { season: "US14", placement: "2", country: "🇺🇸", image: "" },
"Angeria Paris VanMicheals": { season: "US14", placement: "3/4/5", country: "🇺🇸", image: "" },
"Bosco": { season: "US14", placement: "3/4/5", country: "🇺🇸", image: "" },
"Daya Betty": { season: "US14", placement: "3/4/5", country: "🇺🇸", image: "" },
"Deja Skye": { season: "US14", placement: "6/7", country: "🇺🇸", image: "" },
"Jorgeous": { season: "US14", placement: "6/7", country: "🇺🇸", image: "" },
"Jasmine Kennedie": { season: "US14", placement: "8", country: "🇺🇸", image: "" },
"Kerri Colby": { season: "US14", placement: "9", country: "🇺🇸", image: "" },
"Maddy Morphosis": { season: "US14", placement: "10", country: "🇺🇸", image: "" },
"Orion Story": { season: "US14", placement: "11", country: "🇺🇸", image: "" },
"Kornbread Jeté": { season: "US14", placement: "12", country: "🇺🇸", image: "" },
"Alyssa Hunter": { season: "US14", placement: "13", country: "🇺🇸", image: "" },
"June Jumbalaya": { season: "US14", placement: "14", country: "🇺🇸", image: "" },
"Sasha Colby": { season: "US15", placement: "1", country: "🇺🇸", image: "" },
"Anetra": { season: "US15", placement: "2", country: "🇺🇸", image: "" },
"Luxx Noir London": { season: "US15", placement: "3/4", country: "🇺🇸", image: "" },
"Mistress Isabelle Brooks": { season: "US15", placement: "3/4", country: "🇺🇸", image: "" },
"Loosey LaDuca": { season: "US15", placement: "5", country: "🇺🇸", image: "" },
"Salina Estitties": { season: "US15", placement: "6", country: "🇺🇸", image: "" },
"Marcia Marcia Marcia": { season: "US15", placement: "7", country: "🇺🇸", image: "" },
"Malaysia Babydoll Foxx": { season: "US15", placement: "8", country: "🇺🇸", image: "" },
"Spice": { season: "US15", placement: "9", country: "🇺🇸", image: "" },
"Jax": { season: "US15", placement: "10", country: "🇺🇸", image: "" },
"Aura Mayari": { season: "US15", placement: "11", country: "🇺🇸", image: "" },
"Robin Fierce": { season: "US15", placement: "12", country: "🇺🇸", image: "" },
"Amethyst": { season: "US15", placement: "13", country: "🇺🇸", image: "" },
"Sugar": { season: "US15", placement: "14", country: "🇺🇸", image: "" },
"Princess Poppy": { season: "US15", placement: "15", country: "🇺🇸", image: "" },
"Irene The Alien": { season: "US15", placement: "16", country: "🇺🇸", image: "" },
"Nymphia Wind": { season: "US16", placement: "1", country: "🇺🇸", image: "" },
"Sapphira Cristál": { season: "US16", placement: "2", country: "🇺🇸", image: "" },
"Plane Jane": { season: "US16", placement: "3/4", country: "🇺🇸", image: "" },
"Q": { season: "US16", placement: "3/4", country: "🇺🇸", image: "" },
"Morphine Love Dion": { season: "US15", placement: "5", country: "🇺🇸", image: "" },
"Dawn": { season: "US16", placement: "6", country: "🇺🇸", image: "" },
"Mhi'ya Iman Le'Paige": { season: "US16", placement: "7", country: "🇺🇸", image: "" },
"Plasma": { season: "US16", placement: "8", country: "🇺🇸", image: "" },
"Xunami Muse": { season: "US16", placement: "9", country: "🇺🇸", image: "" },
"Megami": { season: "US16", placement: "10", country: "🇺🇸", image: "" },
"Geneva Karr": { season: "US16", placement: "11", country: "🇺🇸", image: "" },
"Amanda Tori Meating": { season: "US16", placement: "12", country: "🇺🇸", image: "" },
"Mirage": { season: "US16", placement: "13", country: "🇺🇸", image: "" },
"Hershii LiqCour-Jeté": { season: "US16", placement: "14", country: "🇺🇸", image: "" },
"Onya Nurve": { season: "US17", placement: "1", country: "🇺🇸", image: "" },
"Jewels Sparkles": { season: "US17", placement: "2", country: "🇺🇸", image: "" },
"Lexi Love": { season: "US17", placement: "3/4", country: "🇺🇸", image: "" },
"Sam Star": { season: "US17", placement: "3/4", country: "🇺🇸", image: "" },
"Suzie Toot": { season: "US17", placement: "5", country: "🇺🇸", image: "" },
"Lana Ja'Rae": { season: "US17", placement: "6", country: "🇺🇸", image: "" }, 
"Lydia B. Kollins": { season: "US17", placement: "7", country: "🇺🇸", image: "" },
"Arrietty": { season: "US17", placement: "8", country: "🇺🇸", image: "" },
"Kori King": { season: "US17", placement: "9", country: "🇺🇸", image: "" },
"Acacia Forgot": { season: "US17", placement: "10", country: "🇺🇸", image: "" },
"Crystal Envy": { season: "US17", placement: "11", country: "🇺🇸", image: "" },
"Hormona Lisa": { season: "US17", placement: "12", country: "🇺🇸", image: "" },
"Joella": { season: "US17", placement: "13", country: "🇺🇸", image: "" },
"Lucky Starzzz": { season: "US17", placement: "14", country: "🇺🇸", image: "" },
"Envy Peru": { season: "1", placement: "1", country: "🇳🇱", image: "" },
"Janey Jacké": { season: "1", placement: "2", country: "🇳🇱", image: "" },
"Ma'Ma Queen": { season: "1", placement: "3/4", country: "🇳🇱", image: "" },
"Miss Abby OMG": { season: "1", placement: "3/4", country: "🇳🇱", image: "" },
"ChelseaBoy": { season: "1", placement: "5", country: "🇳🇱", image: "" },
"Sederginne": { season: "1", placement: "6", country: "🇳🇱", image: "" },
"Madame Madness": { season: "1", placement: "7", country: "🇳🇱", image: "" },
"Megan Schoonbrood": { season: "1", placement: "8", country: "🇳🇱", image: "" },
"Patty Pam-Pam": { season: "1", placement: "9", country: "🇳🇱", image: "" },
"Roem": { season: "1", placement: "10", country: "🇳🇱", image: "" },
"Vanessa van Cartier": { season: "2", placement: "1", country: "🇳🇱", image: "" },
"My Little Puny": { season: "2", placement: "2", country: "🇳🇱", image: "" },
"Vivaldi": { season: "2", placement: "3", country: "🇳🇱", image: "" },
"Keta Minaj": { season: "2", placement: "4", country: "🇳🇱", image: "" },
"Tabitha": { season: "2", placement: "5", country: "🇳🇱", image: "" },
"The Countess": { season: "2", placement: "6", country: "🇳🇱", image: "" },
"Ivy-Elyse": { season: "2", placement: "7", country: "🇳🇱", image: "" },
"Love Masisi": { season: "2", placement: "8", country: "🇳🇱", image: "" },
"Reggy B": { season: "2", placement: "9", country: "🇳🇱", image: "" },
"Juicy Kutoure": { season: "2", placement: "10", country: "🇳🇱", image: "" },
"Natalia Pliacam": { season: "1", placement: "1", country: "🇹🇭", image: "" },
"Année Maywong": { season: "1", placement: "2/3", country: "🇹🇭", image: "" },
"Dearis Doll": { season: "1", placement: "2/3", country: "🇹🇭", image: "" },
"B Ella": { season: "1", placement: "4", country: "🇹🇭", image: "" },
"Amadiva": { season: "1", placement: "5/6", country: "🇹🇭", image: "" },
"JAJA": { season: "1", placement: "5/6", country: "🇹🇭", image: "" },
"Petchra": { season: "1", placement: "7", country: "🇹🇭", image: "" },
"Morrigan": { season: "1", placement: "8", country: "🇹🇭", image: "" },
"Bunny Be Fly": { season: "1", placement: "9", country: "🇹🇭", image: "" },
"Meannie Minaj": { season: "1", placement: "10", country: "🇹🇭", image: "" },
"Angele Anang": { season: "2", placement: "1", country: "🇹🇭", image: "" },
"Kana Warrior": { season: "2", placement: "2/3", country: "🇹🇭", image: "" },
"Kandy Zyanide": { season: "2", placement: "2/3", country: "🇹🇭", image: "" },
"Bandit": { season: "2", placement: "4/5", country: "🇹🇭", image: "" },
"Vanda Miss Joaquim": { season: "2", placement: "4/5", country: "🇹🇭", image: "" },
"Srimala": { season: "2", placement: "6", country: "🇹🇭", image: "" },
"Tormai": { season: "2", placement: "7", country: "🇹🇭", image: "" },
"Genie": { season: "2", placement: "8", country: "🇹🇭", image: "" },
"Miss Gimhuay": { season: "2", placement: "9", country: "🇹🇭", image: "" },
"Mocha Diva": { season: "2", placement: "10", country: "🇹🇭", image: "" },
"Maya B'Haro": { season: "2", placement: "11", country: "🇹🇭", image: "" },
"Katy Killer": { season: "2", placement: "12", country: "🇹🇭", image: "" },
"Silver Sonic": { season: "2", placement: "13", country: "🇹🇭", image: "" },
"M Stranger Fox": { season: "2", placement: "14", country: "🇹🇭", image: "" },
"Frankie Wonga": { season: "3", placement: "1", country: "🇹🇭", image: "" },
"Zepee": { season: "3", placement: "2", country: "🇹🇭", image: "" },
"Gawdland": { season: "3", placement: "3/4", country: "🇹🇭", image: "" },
"Spicy Sunshine": { season: "3", placement: "3/4", country: "🇹🇭", image: "" },
"Nane Sphera": { season: "3", placement: "5", country: "🇹🇭", image: "" },
"Gigi Ferocious": { season: "3", placement: "6", country: "🇹🇭", image: "" },
"Siam Phusri": { season: "3", placement: "7", country: "🇹🇭", image: "" },
"Benze Diva": { season: "3", placement: "8", country: "🇹🇭", image: "" },
"Shortgun": { season: "3", placement: "9", country: "🇹🇭", image: "" },
"Kara Might": { season: "3", placement: "10", country: "🇹🇭", image: "" },
"Srirasha Hotsauce": { season: "3", placement: "1", country: "🇹🇭", image: "" },
"Pangina Heals": { season: "UKVTW1", placement: "6", country: "🇹🇭", image: "" },
"The Vivienne": { season: "1", placement: "1", country: "🇬🇧", image: "" },
"Divina De Campo": { season: "1", placement: "2", country: "🇬🇧", image: "" },
"Baga Chipz": { season: "1", placement: "3", country: "🇬🇧", image: "" },
"Cheryl": { season: "1", placement: "4", country: "🇬🇧", image: "" },
"Blu Hydrangea": { season: "1", placement: "5", country: "🇬🇧", image: "" },
"Crystal": { season: "1", placement: "6", country: "🇬🇧", image: "" },
"Sum Ting Wong": { season: "1", placement: "7", country: "🇬🇧", image: "" },
"Vinegar Strokes": { season: "1", placement: "8", country: "🇬🇧", image: "" },
"Scaredy Kat": { season: "1", placement: "9", country: "🇬🇧", image: "" },
"Gothy Kendoll": { season: "1", placement: "10", country: "🇬🇧", image: "" },
"Lawrence Chaney": { season: "2", placement: "1", country: "🇬🇧", image: "" },
"Bimini Bon-Boulash": { season: "2", placement: "2/3", country: "🇬🇧", image: "" },
"Tayce": { season: "2", placement: "2/3", country: "🇬🇧", image: "" },
"Ellie Diamond": { season: "2", placement: "4", country: "🇬🇧", image: "" },
"A'Whora": { season: "2", placement: "5", country: "🇬🇧", image: "" },
"Sister Sister": { season: "2", placement: "6", country: "🇬🇧", image: "" },
"Tia Kofi": { season: "2", placement: "7", country: "🇬🇧", image: "" },
"Joe Black": { season: "2", placement: "8", country: "🇬🇧", image: "" },
"Veronica Green": { season: "2/3", placement: "9", country: "🇬🇧", image: "" },
"Ginny Lemon": { season: "2", placement: "10", country: "🇬🇧", image: "" },
"Asttina Mandella": { season: "2", placement: "11", country: "🇬🇧", image: "" },
"Cherry Valentine": { season: "2", placement: "12", country: "🇬🇧", image: "" },
"Krystal Versace": { season: "3", placement: "1", country: "🇬🇧", image: "" },
"Ella Vaday": { season: "3", placement: "2/3", country: "🇬🇧", image: "" },
"Kitty Scott-Claus": { season: "3", placement: "2/3", country: "🇬🇧", image: "" },
"Vanity Milan": { season: "3", placement: "4", country: "🇬🇧", image: "" },
"Scarlett Harlett": { season: "3", placement: "5", country: "🇬🇧", image: "" },
"Choriza May": { season: "3", placement: "6/7", country: "🇬🇧", image: "" },
"River Medway": { season: "3", placement: "6/7", country: "🇬🇧", image: "" },
"Charity Kase": { season: "3", placement: "8", country: "🇬🇧", image: "" },
"Victoria Scone": { season: "3", placement: "10", country: "🇬🇧", image: "" },
"Elektra Fence": { season: "3", placement: "11", country: "🇬🇧", image: "" },
"Anubis": { season: "3", placement: "12", country: "🇬🇧", image: "" },
"Danny Beard": { season: "4", placement: "1", country: "🇬🇧", image: "" },
"Cheddar Gorgeous": { season: "4", placement: "2", country: "🇬🇧", image: "" },
"Black Peppa": { season: "4", placement: "3/4", country: "🇬🇧", image: "" },
"Jonbers Blonde": { season: "4", placement: "3/4", country: "🇬🇧", image: "" },
"Pixie Polite": { season: "4", placement: "5", country: "🇬🇧", image: "" },
"Dakota Schiffer": { season: "4", placement: "6", country: "🇬🇧", image: "" },
"Le Fil": { season: "4", placement: "7", country: "🇬🇧", image: "" },
"Baby": { season: "4", placement: "8", country: "🇬🇧", image: "" },
"Sminty Drop": { season: "4", placement: "9", country: "🇬🇧", image: "" },
"Copper Topp": { season: "4", placement: "10", country: "🇬🇧", image: "" },
"Starlet": { season: "4", placement: "11", country: "🇬🇧", image: "" },
"Just May": { season: "4", placement: "12", country: "🇬🇧", image: "" },
"Ginger Johnson": { season: "5", placement: "1", country: "🇬🇧", image: "" },
"Michael Marouli": { season: "5", placement: "2", country: "🇬🇧", image: "" },
"Tomara Thomas": { season: "5", placement: "3", country: "🇬🇧", image: "" },
"DeDeLicious": { season: "5", placement: "4", country: "🇬🇧", image: "" },
"Kate Butch": { season: "5", placement: "5", country: "🇬🇧", image: "" },
"Cara Melle": { season: "5", placement: "6", country: "🇬🇧", image: "" },
"Vicki Vivacious": { season: "5", placement: "7", country: "🇬🇧", image: "" },
"Banksie": { season: "5", placement: "8", country: "🇬🇧", image: "" },
"Miss Naomi": { season: "5", placement: "9", country: "🇬🇧", image: "" },
"Alexis Saint-Pete": { season: "5", placement: "10", country: "🇬🇧", image: "" },
"Kyran Thrax": { season: "6", placement: "1", country: "🇬🇧", image: "" },
"La Voix": { season: "6", placement: "2", country: "🇬🇧", image: "" },
"Marmalade": { season: "6", placement: "3/4", country: "🇬🇧", image: "" },
"Rileasa": { season: "6", placement: "3/4", country: "🇬🇧", image: "" },
"Lill": { season: "6", placement: "5", country: "🇬🇧", image: "" },
"Charra Tea": { season: "6", placement: "6", country: "🇬🇧", image: "" },
"Actavia": { season: "6", placement: "7", country: "🇬🇧", image: "" },
"Chanel O'Conor": { season: "6", placement: "8", country: "🇬🇧", image: "" },
"Kiki Snatch": { season: "6", placement: "9", country: "🇬🇧", image: "" },
"Zahirah Zapanta": { season: "6", placement: "10", country: "🇬🇧", image: "" },
"Dita Garbo": { season: "6", placement: "11", country: "🇬🇧", image: "" },
"Saki Yew": { season: "6", placement: "12", country: "🇬🇧", image: "" },
"Priyanka": { season: "1", placement: "1", country: "🇨🇦", image: "" },
"Rita Baga": { season: "1", placement: "2/3", country: "🇨🇦", image: "" },
"Scarlett BoBo": { season: "1", placement: "2/3", country: "🇨🇦", image: "" },
"Jimbo": { season: "1", placement: "4", country: "🇨🇦", image: "" },
"Lemon": { season: "1", placement: "5", country: "🇨🇦", image: "" },
"Ilona Verley": { season: "1", placement: "6", country: "🇨🇦", image: "" },
"BOA": { season: "1", placement: "7", country: "🇨🇦", image: "" },
"Kiara": { season: "1", placement: "8", country: "🇨🇦", image: "" },
"Tynomi Banks": { season: "1", placement: "9", country: "🇨🇦", image: "" },
"Anastarzia Anaquway": { season: "1", placement: "10", country: "🇨🇦", image: "" },
"Kyne": { season: "1", placement: "11", country: "🇨🇦", image: "" },
"Juice Boxx": { season: "1", placement: "12", country: "🇨🇦", image: "" },
"Icesis Couture": { season: "2", placement: "1", country: "🇨🇦", image: "" },
"Kendall Gender": { season: "2", placement: "2/3", country: "🇨🇦", image: "" },
"Pythia": { season: "2", placement: "2/3", country: "🇨🇦", image: "" },
"Gia Metric": { season: "2", placement: "4", country: "🇨🇦", image: "" },
"Adriana": { season: "2", placement: "5", country: "🇨🇦", image: "" },
"Kimora Amour": { season: "2", placement: "6", country: "🇨🇦", image: "" },
"Synthia Kiss": { season: "2", placement: "7", country: "🇨🇦", image: "" },
"Eve 6000": { season: "2", placement: "8", country: "🇨🇦", image: "" },
"Suki Doll": { season: "2", placement: "9", country: "🇨🇦", image: "" },
"Stephanie Prince": { season: "2", placement: "10", country: "🇨🇦", image: "" },
"Océane Aqua-Black": { season: "2", placement: "11", country: "🇨🇦", image: "" },
"Beth": { season: "2", placement: "12", country: "🇨🇦", image: "" },
"Giséle Lullaby": { season: "3", placement: "1", country: "🇨🇦", image: "" },
"Jada Shada Hudson": { season: "3", placement: "2", country: "🇨🇦", image: "" },
"Kimmy Couture": { season: "3", placement: "3/4", country: "🇨🇦", image: "" },
"Miss Fiercalicious": { season: "3", placement: "3/4", country: "🇨🇦", image: "" },
"Vivian Vanderpuss": { season: "3", placement: "5", country: "🇨🇦", image: "" },
"Irma Gerd": { season: "3", placement: "6", country: "🇨🇦", image: "" },
"Bombae": { season: "3", placement: "7", country: "🇨🇦", image: "" },
"Lady Boom Boom": { season: "3", placement: "8", country: "🇨🇦", image: "" },
"Kaos": { season: "3", placement: "9", country: "🇨🇦", image: "" },
"Chelazon Leroux": { season: "3", placement: "10", country: "🇨🇦", image: "" },
"Miss Moço": { season: "3", placement: "11", country: "🇨🇦", image: "" },
"Halal Bae": { season: "3", placement: "12", country: "🇨🇦", image: "" },
"Venus": { season: "4", placement: "1", country: "🇨🇦", image: "" },
"Aurora Matrix": { season: "4", placement: "2", country: "🇨🇦", image: "" },
"Denim": { season: "4", placement: "3/4", country: "🇨🇦", image: "" },
"Nearah Nuff": { season: "4", placement: "3/4", country: "🇨🇦", image: "" },
"Melinda Verga": { season: "4", placement: "5", country: "🇨🇦", image: "" },
"Kiki Coe": { season: "4", placement: "6", country: "🇨🇦", image: "" },
"Aimee Yonce Shennel": { season: "4", placement: "7", country: "🇨🇦", image: "" },
"Kitten Kaboodle": { season: "4", placement: "8", country: "🇨🇦", image: "" },
"Luna DuBois": { season: "4", placement: "9", country: "🇨🇦", image: "" },
"The Girlfriend Experience": { season: "4", placement: "10", country: "🇨🇦", image: "" },
"Sisi Superstar": { season: "4", placement: "11", country: "🇨🇦", image: "" },
"The Virgo Queen": { season: "5", placement: "1", country: "🇨🇦", image: "" },
"Makayla Couture": { season: "5", placement: "2", country: "🇨🇦", image: "" },
"Helena Poison": { season: "5", placement: "3/4", country: "🇨🇦", image: "" },
"Minhi Wang": { season: "5", placement: "3/4", country: "🇨🇦", image: "" },
"Perla": { season: "5", placement: "5", country: "🇨🇦", image: "" },
"Xana": { season: "5", placement: "6", country: "🇨🇦", image: "" },
"Uma Gahd": { season: "5", placement: "7", country: "🇨🇦", image: "" },
"Jaylene Tyme": { season: "5", placement: "8", country: "🇨🇦", image: "" },
"Sanjina Dabish Queen": { season: "5", placement: "9", country: "🇨🇦", image: "" },
"Tiffany Ann Co.": { season: "5", placement: "10", country: "🇨🇦", image: "" },
"Tara Nova": { season: "5", placement: "11", country: "🇨🇦", image: "" },
"Kita Mean": { season: "1", placement: "1", country: "🇦🇺", image: "" },
"Art Simone": { season: "1", placement: "2", country: "🇦🇺", image: "" },
"Karen From Finance": { season: "1", placement: "3/4", country: "🇦🇺", image: "" },
"Scarlet Adams": { season: "1", placement: "3/4", country: "🇦🇺", image: "" },
"Elektra Shock": { season: "1", placement: "5", country: "🇦🇺", image: "" },
"Maxi Shield": { season: "1", placement: "6", country: "🇦🇺", image: "" },
"Etcetera Etcetera": { season: "1", placement: "7", country: "🇦🇺", image: "" },
"Anita Wigl'it": { season: "1", placement: "8", country: "🇦🇺", image: "" },
"Coco Jumbo": { season: "1", placement: "9", country: "🇦🇺", image: "" },
"Jojo Zaho": { season: "1", placement: "10", country: "🇦🇺", image: "" },
"Spankie Jackzon": { season: "2", placement: "1", country: "🇦🇺", image: "" },
"Hannah Conda": { season: "2", placement: "2/3", country: "🇦🇺", image: "" },
"Kween Kong": { season: "2", placement: "2/3", country: "🇦🇺", image: "" },
"Molly Poppinz": { season: "2", placement: "4", country: "🇦🇺", image: "" },
"Beverly Kills": { season: "2", placement: "5", country: "🇦🇺", image: "" },
"Yuri Guaii": { season: "2", placement: "6", country: "🇦🇺", image: "" },
"Minnie Cooper": { season: "2", placement: "7", country: "🇦🇺", image: "" },
"Pomara Fifth": { season: "2", placement: "8", country: "🇦🇺", image: "" },
"Aubrey Haive": { season: "2", placement: "9", country: "🇦🇺", image: "" },
"Faúx Fúr": { season: "2", placement: "10", country: "🇦🇺", image: "" },
"Isis Avis Loren": { season: "3", placement: "1", country: "🇦🇺", image: "" },
"Gabriella Labucci": { season: "3", placement: "2", country: "🇦🇺", image: "" },
"Flor": { season: "3", placement: "3", country: "🇦🇺", image: "" },
"Hollywould Star": { season: "3", placement: "4", country: "🇦🇺", image: "" },
"Bumpa Love": { season: "3", placement: "5", country: "🇦🇺", image: "" },
"Ashley Madison": { season: "3", placement: "6", country: "🇦🇺", image: "" },
"Rita Menu": { season: "3", placement: "7", country: "🇦🇺", image: "" },
"Ivanna Drink": { season: "3", placement: "8", country: "🇦🇺", image: "" },
"Ivory Glaze": { season: "3", placement: "9", country: "🇦🇺", image: "" },
"Amyl": { season: "3", placement: "10", country: "🇦🇺", image: "" },
"Lazy Susan": { season: "4", placement: "1", country: "🇦🇺", image: "" },
"Mandy Moobs": { season: "4", placement: "2/3", country: "🇦🇺", image: "" },
"Vybe": { season: "4", placement: "2/3", country: "🇦🇺", image: "" },
"Freya Armani": { season: "4", placement: "4", country: "🇦🇺", image: "" },
"Nikita Iman": { season: "4", placement: "5", country: "🇦🇺", image: "" },
"Max Drag Queen": { season: "4", placement: "6", country: "🇦🇺", image: "" },
"Brenda Bressed": { season: "4", placement: "7", country: "🇦🇺", image: "" },
"Lucina Innocence": { season: "4", placement: "8", country: "🇦🇺", image: "" },
"Karna Ford": { season: "4", placement: "9", country: "🇦🇺", image: "" },
"Olivia Dreams": { season: "4", placement: "10", country: "🇦🇺", image: "" },
"Carmen Farala": { season: "1", placement: "1", country: "🇪🇸", image: "" },
"Killer Queen": { season: "1", placement: "2/3", country: "🇪🇸", image: "" },
"Sagittaria": { season: "1", placement: "2/3", country: "🇪🇸", image: "" },
"Pupi Poisson": { season: "1", placement: "4", country: "🇪🇸", image: "" },
"Dovima Nurmi": { season: "1", placement: "5", country: "🇪🇸", image: "" },
"Hugáceo Crujiente": { season: "1", placement: "6", country: "🇪🇸", image: "" },
"Arantxa Castilla La Mancha": { season: "1", placement: "7", country: "🇪🇸", image: "" },
"Inti": { season: "1", placement: "8", country: "🇪🇸", image: "" },
"Drag Vulcano": { season: "1", placement: "9", country: "🇪🇸", image: "" },
"The Macarena": { season: "1/3", placement: "10", country: "🇪🇸", image: "" },
"Sharonne": { season: "2", placement: "1", country: "🇪🇸", image: "" },
"Estrella Xtravaganza": { season: "2", placement: "2/3", country: "🇪🇸", image: "" },
"Venedita Von Däsh": { season: "2", placement: "2/3", country: "🇪🇸", image: "" },
"Marina": { season: "2", placement: "4", country: "🇪🇸", image: "" },
"Juriji Der Klee": { season: "2", placement: "5", country: "🇪🇸", image: "" },
"Drag Sethlas": { season: "2", placement: "6", country: "🇪🇸", image: "" },
"Diamante Merybrown": { season: "2", placement: "7", country: "🇪🇸", image: "" },
"Onyx": { season: "2", placement: "8", country: "🇪🇸", image: "" },
"Jota Carajota": { season: "2", placement: "9", country: "🇪🇸", image: "" },
"Samantha Ballentines": { season: "2", placement: "10", country: "🇪🇸", image: "" },
"Ariel Rec": { season: "2", placement: "11", country: "🇪🇸", image: "" },
"Marisa Prisa": { season: "3", placement: "12", country: "🇪🇸", image: "" },
"Pitita": { season: "3", placement: "1", country: "🇪🇸", image: "" },
"Vania Vainilla": { season: "3", placement: "2", country: "🇪🇸", image: "" },
"Hornella Góngora": { season: "3", placement: "3/4", country: "🇪🇸", image: "" },
"Kelly Roller": { season: "3", placement: "3/4", country: "🇪🇸", image: "" },
"Clover Bish": { season: "3", placement: "5", country: "🇪🇸", image: "" },
"Bestiah": { season: "3", placement: "6", country: "🇪🇸", image: "" },
"Pakita": { season: "3", placement: "7/8", country: "🇪🇸", image: "" },
"Pink Chadora": { season: "3", placement: "7/8", country: "🇪🇸", image: "" },
"Visa": { season: "3", placement: "9", country: "🇪🇸", image: "" },
"The Macarena": { season: "1/3", placement: "10", country: "🇪🇸", image: "" },
"Chanel Anorex": { season: "3", placement: "11", country: "🇪🇸", image: "" },
"Drag Chuchi": { season: "3", placement: "12", country: "🇪🇸", image: "" },
"Maria Edilia": { season: "3", placement: "13", country: "🇪🇸", image: "" },
"Le Cocó": { season: "4", placement: "1", country: "🇪🇸", image: "" },
"La Bella Vampi": { season: "4", placement: "2", country: "🇪🇸", image: "" },
"Chloe Vittu": { season: "4", placement: "3", country: "🇪🇸", image: "" },
"La Niña Delantro": { season: "4", placement: "4", country: "🇪🇸", image: "" },
"Mariana Stars": { season: "4", placement: "5", country: "🇪🇸", image: "" },
"Megui Yeillow": { season: "4", placement: "6", country: "🇪🇸", image: "" },
"Angelita La Perversa": { season: "4", placement: "7", country: "🇪🇸", image: "" },
"Miss Khristo": { season: "4", placement: "8", country: "🇪🇸", image: "" },
"Kelly Passa?": { season: "4", placement: "9", country: "🇪🇸", image: "" },
"Dita Dubois": { season: "4", placement: "10", country: "🇪🇸", image: "" },
"Porca TheClubKid": { season: "4", placement: "11", country: "🇪🇸", image: "" },
"Shani LeSanta": { season: "4", placement: "12", country: "🇪🇸", image: "" },
"Elecktra Bionic": { season: "1", placement: "1", country: "🇮🇹", image: "" },
"Farida Kant": { season: "1", placement: "2/3", country: "🇮🇹", image: "" },
"Le Riche": { season: "1", placement: "2/3", country: "🇮🇹", image: "" },
"Luquisha Lubamba": { season: "1", placement: "4", country: "🇮🇹", image: "" },
"Ava Hangar": { season: "1", placement: "5", country: "🇮🇹", image: "" },
"Divinity": { season: "1", placement: "6", country: "🇮🇹", image: "" },
"Enorma Jean": { season: "1", placement: "7", country: "🇮🇹", image: "" },
"Ivana Vamp": { season: "1", placement: "8", country: "🇮🇹", image: "" },
"La Diamond": { season: "2", placement: "1", country: "🇮🇹", image: "" },
"Aura Eternal": { season: "2", placement: "2/3", country: "🇮🇹", image: "" },
"Nehellenia": { season: "2", placement: "2/3", country: "🇮🇹", image: "" },
"La Petite Noire": { season: "2", placement: "4", country: "🇮🇹", image: "" },
"Skandalove": { season: "2", placement: "5", country: "🇮🇹", image: "" },
"Gioffré": { season: "2", placement: "6", country: "🇮🇹", image: "" },
"Panthera Virus": { season: "2", placement: "7", country: "🇮🇹", image: "" },
"Obama": { season: "2", placement: "8", country: "🇮🇹", image: "" },
"Tanissa Yoncè": { season: "2", placement: "9", country: "🇮🇹", image: "" },
"Narciso": { season: "2", placement: "10", country: "🇮🇹", image: "" },
"Lina Galore": { season: "3", placement: "1", country: "🇮🇹", image: "" },
"Melissa Bianchini": { season: "3", placement: "2", country: "🇮🇹", image: "" },
"La Sheeva": { season: "3", placement: "3/4", country: "🇮🇹", image: "" },
"Silvana Della Magliana": { season: "3", placement: "3/4", country: "🇮🇹", image: "" },
"Sypario": { season: "3", placement: "5", country: "🇮🇹", image: "" },
"Leila Yarn": { season: "3", placement: "6", country: "🇮🇹", image: "" },
"La Prada": { season: "3", placement: "7", country: "🇮🇹", image: "" },
"Sissy Lea": { season: "3", placement: "8", country: "🇮🇹", image: "" },
"Morgana Cosmica": { season: "3", placement: "9", country: "🇮🇹", image: "" },
"Lightning Aurora": { season: "3", placement: "10", country: "🇮🇹", image: "" },
"Vezirja": { season: "3", placement: "11", country: "🇮🇹", image: "" },
"Amy Krania": { season: "3", placement: "12", country: "🇮🇹", image: "" },
"Adriana Picasso": { season: "3", placement: "13", country: "🇮🇹", image: "" },
"Paloma": { season: "1", placement: "1", country: "🇫🇷", image: "" },
"La Grande Dame": { season: "1", placement: "2/3", country: "🇫🇷", image: "" },
"Soa de Muse": { season: "1", placement: "2/3", country: "🇫🇷", image: "" },
"Lolita Banana": { season: "1", placement: "4", country: "🇫🇷", image: "" },
"La Big Bertha": { season: "1", placement: "5", country: "🇫🇷", image: "" },
"Elips": { season: "1", placement: "6", country: "🇫🇷", image: "" },
"Kam Hugh": { season: "1", placement: "7", country: "🇫🇷", image: "" },
"La Briochée": { season: "1", placement: "8", country: "🇫🇷", image: "" },
"Lova Ladiva": { season: "1", placement: "9", country: "🇫🇷", image: "" },
"La Kahena": { season: "1", placement: "10", country: "🇫🇷", image: "" },
"Keiona": { season: "2", placement: "1", country: "🇫🇷", image: "" },
"Sara Forever": { season: "2", placement: "2", country: "🇫🇷", image: "" },
"Mami Watta": { season: "2", placement: "3/4", country: "🇫🇷", image: "" },
"Punani": { season: "2", placement: "3/4", country: "🇫🇷", image: "" },
"Piche": { season: "2", placement: "5", country: "🇫🇷", image: "" },
"Cookie Kunty": { season: "2", placement: "6", country: "🇫🇷", image: "" },
"Moon": { season: "2", placement: "7", country: "🇫🇷", image: "" },
"Ginger Bitch": { season: "2", placement: "8", country: "🇫🇷", image: "" },
"Kitty Space": { season: "2", placement: "9", country: "🇫🇷", image: "" },
"Vespi": { season: "2", placement: "10", country: "🇫🇷", image: "" },
"Rose": { season: "2", placement: "11", country: "🇫🇷", image: "" },
"Le Filip": { season: "3", placement: "1", country: "🇫🇷", image: "" },
"Ruby On The Nail": { season: "3", placement: "2", country: "🇫🇷", image: "" },
"Leona Winter": { season: "3", placement: "3/4", country: "🇫🇷", image: "" },
"Lula Strega": { season: "3", placement: "3/4", country: "🇫🇷", image: "" },
"Misty Phoenix": { season: "3", placement: "5", country: "🇫🇷", image: "" },
"Perseo": { season: "3", placement: "6", country: "🇫🇷", image: "" },
"Norma Bell": { season: "3", placement: "7", country: "🇫🇷", image: "" },
"Edeha Noire": { season: "3", placement: "8", country: "🇫🇷", image: "" },
"Magnetica": { season: "3", placement: "9", country: "🇫🇷", image: "" },
"Afrodite Amour": { season: "3", placement: "10", country: "🇫🇷", image: "" },
"Precious Paula Nicole": { season: "1", placement: "1", country: "🇵🇭", image: "" },
"Marina Summers": { season: "1", placement: "2", country: "🇵🇭", image: "" },
"Xilhouete": { season: "1", placement: "3/4", country: "🇵🇭", image: "" },
"Eva Le Queen": { season: "1", placement: "3/4", country: "🇵🇭", image: "" },
"Minty Fresh": { season: "1", placement: "5", country: "🇵🇭", image: "" },
"Brigiding": { season: "1", placement: "6", country: "🇵🇭", image: "" },
"Viñas Deluxe": { season: "1", placement: "7", country: "🇵🇭", image: "" },
"Lady Morgana": { season: "1", placement: "8", country: "🇵🇭", image: "" },
"Turing": { season: "1", placement: "9", country: "🇵🇭", image: "" },
"Gigi Era": { season: "1", placement: "10", country: "🇵🇭", image: "" },
"Corazon": { season: "1", placement: "11", country: "🇵🇭", image: "" },
"Prince": { season: "1", placement: "12", country: "🇵🇭", image: "" },
"Captivating Katkat": { season: "2", placement: "1", country: "🇵🇭", image: "" },
"Arizona Brandy": { season: "2", placement: "2", country: "🇵🇭", image: "" },
"M1ss Jade So": { season: "2", placement: "3/4", country: "🇵🇭", image: "" },
"Bernie": { season: "2", placement: "3/4", country: "🇵🇭", image: "" },
"Hana Beshie": { season: "2", placement: "5/6", country: "🇵🇭", image: "" },
"ØV Cünt": { season: "2", placement: "5/6", country: "🇵🇭", image: "" },
"DeeDee Marié Holliday": { season: "2", placement: "7", country: "🇵🇭", image: "" },
"Matilduh": { season: "2", placement: "8", country: "🇵🇭", image: "" },
"Veruschka Levels": { season: "2", placement: "9", country: "🇵🇭", image: "" },
"Tiny Deluxe": { season: "2", placement: "10", country: "🇵🇭", image: "" },
"Astrid Mercury": { season: "2", placement: "11", country: "🇵🇭", image: "" },
"Nicole Pardaux": { season: "2", placement: "12", country: "🇵🇭", image: "" },
"Maxie": { season: "3", placement: "1", country: "🇵🇭", image: "" },
"Khianna": { season: "3", placement: "2", country: "🇵🇭", image: "" },
"Angel": { season: "3", placement: "3/4", country: "🇵🇭", image: "" },
"Tita Baby": { season: "3", placement: "3/4", country: "🇵🇭", image: "" },
"Zymba Ding": { season: "3", placement: "5", country: "🇵🇭", image: "" },
"Myx Chanel": { season: "3", placement: "6", country: "🇵🇭", image: "" },
"Popstar Bench": { season: "3", placement: "7", country: "🇵🇭", image: "" },
"John Fedellaga": { season: "3", placement: "8", country: "🇵🇭", image: "" },
"J Quinn": { season: "3", placement: "9", country: "🇵🇭", image: "" },
"Yudipota": { season: "3", placement: "10", country: "🇵🇭", image: "" },
"Versex": { season: "3", placement: "11", country: "🇵🇭", image: "" },
"Drag Couenne": { season: "1", placement: "1", country: "🇧🇪", image: "" },
"Athena Sorgelikis": { seaso: "1", placement: "2", country: "🇧🇪", image: "" },
"Susan": { season: "1", placement: "3", country: "🇧🇪", image: "" },
"Mademoiselle Boop": { season: "1", placement: "4", country: "🇧🇪", image: "" },
"Peach": { season: "1", placement: "5", country: "🇧🇪", image: "" },
"Valenciaga": { season: "1", placement: "6", country: "🇧🇪", image: "" },
"Mocca Bone": { season: "1", placement: "7", country: "🇧🇪", image: "" },
"Edna Sorgelsen": { season: "1", placement: "8", country: "🇧🇪", image: "" },
"Amanda Tears": { season: "1", placement: "9", country: "🇧🇪", image: "" },
"Brittany Von Bottoks": { season: "1", placement: "10", country: "🇧🇪", image: "" },
"Alvilda": { season: "2", placement: "1", country: "🇧🇪", image: "" },
"La Veuve": { season: "2", placement: "2", country: "🇧🇪", image: "" },
"Loulou Velvet": { season: "2", placement: "3/4", country: "🇧🇪", image: "" },
"Gabanna": { season: "2", placement: "3/4", country: "🇧🇪", image: "" },
"Chloe Clarke": { season: "2", placement: "5", country: "🇧🇪", image: "" },
"Star": { season: "2", placement: "6", country: "🇧🇪", image: "" },
"Morphae": { season: "2", placement: "7", country: "🇧🇪", image: "" },
"Madame Yoko": { season: "2", placement: "8", country: "🇧🇪", image: "" },
"Sarah Logan": { season: "2", placement: "9", country: "🇧🇪", image: "" },
"Admira Thunderpussy": { season: "1", placement: "1", country: "🇸🇪", image: "" },
"Fontana": { season: "1", placement: "2", country: "🇸🇪", image: "" },
"Vanity Vain": { season: "1", placement: "3", country: "🇸🇪", image: "" },
"Elecktra": { season: "1", placement: "4", country: "🇸🇪", image: "" },
"Antonina Nutshell": { season: "1", placement: "5", country: "🇸🇪", image: "" },
"Santana Sexmachine": { season: "1", placement: "6", country: "🇸🇪", image: "" },
"Imaa Queen": { season: "1", placement: "7", country: "🇸🇪", image: "" },
"Endigo": { season: "1", placement: "8", country: "🇸🇪", image: "" },
"Almighty Aphroditey": { season: "1", placement: "9", country: "🇸🇪", image: "" },
"Cristian Peralta": { season: "1", placement: "1", country: "🇲🇽", image: "" },
"Gala Varo": { season: "1", placement: "2/3/4", country: "🇲🇽", image: "" },
"Matraka": { season: "1", placement: "2/3/4", country: "🇲🇽", image: "" },
"Regina Voce": { season: "1", placement: "2/3/4", country: "🇲🇽", image: "" },
"Lady Kero": { season: "1", placement: "5", country: "🇲🇽", image: "" },
"Margaret Y Ya": { season: "1", placement: "6", country: "🇲🇽", image: "" },
"Argennis": { season: "1", placement: "7", country: "🇲🇽", image: "" },
"Serena Morena": { season: "1", placement: "8", country: "🇲🇽", image: "" },
"Pixie Pixie": { season: "1", placement: "9", country: "🇲🇽", image: "" },
"Vermelha Noir": { season: "1", placement: "10", country: "🇲🇽", image: "" },
"Miss Vallarta": { season: "1", placement: "11", country: "🇲🇽", image: "" },
"Leexa Fox": { season: "2", placement: "1", country: "🇲🇽", image: "" },
"Eva Blunt": { season: "2", placement: "2/3/4", country: "🇲🇽", image: "" },
"Horacio Potasio": { season: "2", placement: "2/3/4", country: "🇲🇽", image: "" },
"Jenary Bloom": { season: "2", placement: "2/3/4", country: "🇲🇽", image: "" },
"Elektra Vandergeld": { season: "2", placement: "5", country: "🇲🇽", image: "" },
"Unique": { season: "2", placement: "6", country: "🇲🇽", image: "" },
"Luna Lansman": { season: "2", placement: "7", country: "🇲🇽", image: "" },
"Suculenta": { season: "2", placement: "8", country: "🇲🇽", image: "" },
"Ava Pocket": { season: "2", placement: "9", country: "🇲🇽", image: "" },
"Garçonne": { season: "2", placement: "10", country: "🇲🇽", image: "" },
"María Bonita": { season: "2", placement: "11", country: "🇲🇽", image: "" },
"Nina de la Fuente": { season: "2", placement: "12", country: "🇲🇽", image: "" },
"Ignus Ars": { season: "2", placement: "13", country: "🇲🇽", image: "" },
"Organzza": { season: "1", placement: "1", country: "🇧🇷", image: "" },
"Betina Polaroid": { season: "1", placement: "2/3/4", country: "🇧🇷", image: "" },
"Hellena Malditta": { season: "1", placement: "2/3/4", country: "🇧🇷", image: "" },
"Miranda Lebrão": { season: "1", placement: "2/3/4", country: "🇧🇷", image: "" },
"Shannon Skarllet": { season: "1", placement: "5", country: "🇧🇷", image: "" },
"Naza": { season: "1", placement: "6", country: "🇧🇷", image: "" },
"Dallas de Vil": { season: "1", placement: "7", country: "🇧🇷", image: "" },
"Rubi Ocean": { season: "1", placement: "8", country: "🇧🇷", image: "" },
"Aquarela": { season: "1", placement: "9", country: "🇧🇷", image: "" },
"Melusine Sparkle": { season: "1", placement: "10", country: "🇧🇷", image: "" },
"Tristan Soledade": { season: "1", placement: "11", country: "🇧🇷", image: "" },
"Diva More": { season: "1", placement: "12", country: "🇧🇷", image: "" },
"Pandora Nox": { season: "1", placement: "1", country: "🇩🇪", image: "" },
"Metamorkid": { season: "1", placement: "2/3", country: "🇩🇪", image: "" },
"Yvonne Nightstand": { season: "1", placement: "2/3", country: "🇩🇪", image: "" },
"Kelly Heelton": { season: "1", placement: "4", country: "🇩🇪", image: "" },
"Loreley Rivers": { season: "1", placement: "5", country: "🇩🇪", image: "" },
"Victoria Shakespears": { season: "1", placement: "6", country: "🇩🇪", image: "" },
"Nikita Vegaz": { season: "1", placement: "7", country: "🇩🇪", image: "" },
"Tessa Testicle": { season: "1", placement: "8", country: "🇩🇪", image: "" },
"LéLé Cocoon": { season: "1", placement: "9", country: "🇩🇪", image: "" },
"The Only Naomy": { season: "1", placement: "10", country: "🇩🇪", image: "" },
"Barbie Q": { season: "1", placement: "11", country: "🇩🇪", image: "" },
 };
